### ISSUE TITLE
[Docs] Update readme with plugin description

### ISSUE THREAD

**Issue by leecalcote** [meshery/helm-kanvas-snapshot#19]
### Current State
The readme doesn't specifically describe the helm plugin.

### Desired State
Most or all of the Meshery content is replaced.

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by jamieplu** [comment]
@Aijeyomah do you want or need help here?

**Comment by leecalcote** [comment]
@Aijeyomah, I went ahead and took care of this.
