### ISSUE TITLE
[Chore] Three golangci-lint check failures

### ISSUE THREAD

**Issue by leecalcote** [meshery/helm-kanvas-snapshot#26]
### Current Behavior
A few golangci-lint checks are failing. See https://github.com/meshery/helm-kanvas-snapshot/actions/runs/11098994599/job/30832523474#step:4:26

### Screenshots/Logs
```
run golangci-lint
  Running [/Users/runner/golangci-lint-1.59.1-darwin-arm64/golangci-lint run --path-prefix=./cmd/kanvas-snapshot --timeout 10m --verbose] in [/Users/runner/work/helm-kanvas-snapshot/helm-kanvas-snapshot/cmd/kanvas-snapshot] ...
  Error: cmd/kanvas-snapshot/main.go:178:13: Error return value of `io.ReadAll` is not checked (errcheck)
  		io.ReadAll(resp.Body)
  		          ^
  Error: cmd/kanvas-snapshot/main.go:254:44: Error return value of `generateKanvasSnapshotCmd.MarkFlagRequired` is not checked (errcheck)
  	generateKanvasSnapshotCmd.MarkFlagRequired("file")
  	                                          ^
  Error: cmd/kanvas-snapshot/main.go:255:44: Error return value of `generateKanvasSnapshotCmd.MarkFlagRequired` is not checked (errcheck)
  	generateKanvasSnapshotCmd.MarkFlagRequired("email")
```

### Environment

- **Host OS:** Mac Linux Windows
- **Platform:** Docker or Kubernetes
- **Meshery Server Version:** stable-v
- **Meshery Client Version:** stable-v

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by fitzergerald** [comment]
Are these being worked on?
