### ISSUE TITLE
[Docs] Add this extension to docs.meshery.io's list of extensions under Extensibility

### ISSUE THREAD

**Issue by winkletinkle** [meshery/helm-kanvas-snapshot#32]
### Desired State

---

### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 📚 [Instructions for contributing to documentation](https://docs.meshery.io/project/contributing/contributing-docs)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by hamza-mohd** [comment]
Here's a link to the extensions page - https://docs.meshery.io/extensions/

**Comment by leecalcote** [comment]
THanks!

**Comment by deepikaa0402** [comment]
Hi! Which extension is to be added? and can you please assign this issue to me?

**Comment by aryannargotra** [comment]
Plz Correct me If I'm wrong, but  the 
desired behaviour is to put in under [🛠 Integrations & Extensions](https://docs.meshery.io/extensibility) rather than as a separate [🦾 Extensions ↆ](https://docs.meshery.io/extensions) ?

**Comment by hamza-mohd** [comment]
Ok, I'll correct you. You're wrong. :grinning:

**Comment by hamza-mohd** [comment]
Thanks for taking care of this @winkletinkle
