### ISSUE TITLE
Lint check failures

### ISSUE THREAD

**Issue by leecalcote** [meshery/helm-kanvas-snapshot#54]
### Current Behavior
<img width="1115" alt="Screenshot 2024-11-05 at 4 07 29 PM" src="https://github.com/user-attachments/assets/3fd78da0-dbb2-43fb-8cd8-d63bdb86c847">

### Expected Behavior
All lint checks pass

---
### Contributor [Guides](https://docs.meshery.io/project/contributing) and [Handbook](https://layer5.io/community/handbook)
- 🛠 [Meshery Build & Release Strategy](https://docs.meshery.io/project/contributing/build-and-release)
- 📚 [Instructions for contributing to documentation](https://github.com/meshery/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)
   - Meshery documentation [site](https://docs.meshery.io/) and [source](https://github.com/meshery/meshery/tree/master/docs)
- 🎨 Wireframes and [designs for Meshery UI](https://www.figma.com/file/SMP3zxOjZztdOLtgN4dS2W/Meshery-UI) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Discussion Forum](http://discuss.meshery.io) and [Community Slack](https://slack.meshery.io)

**Comment by theBeginner86** [comment]
This has been fixed. So closing this.
